### PR TITLE
Increase airport table field lengths

### PR DESCRIPTION
**Pull request by kingjon3377**
I'd like to increase the length of both fields in the table of airports. I've found a dataset of (nearly) all airports in the world, and many have a 4-character code, a "name" over 45 characters, or both.

### CODE REVIEW

**Review by al-amine — APPROVED** [review]
Totally agree.

**Review by STOzaki — APPROVED** [review]
Looks good

**Review by STOzaki — CHANGES_REQUESTED** [review]
Wait, we are going to need to change char(4) to varchar(4) because some codes are still 3 letters.

**Comment by kingjon3377** [comment]
The difference between `CHAR` and `VARCHAR` is in how they are allocated; a `CHAR(4)` can hold only-3-character (or only-1-character) strings, but they take up as much space as a 4-character string. On the other hand, a `VARCHAR` is a pointer to a dynamically allocated string. This wastes a character's worth of space per row for 3-character codes (except that the `VARCHAR` pointer would probably have that much overhead, I guess), but will be faster to read.

**Review by STOzaki — APPROVED** [review]
Okay, that makes sense

**Pull request merged**
